name: anti_propa_gondons
description: Application for destroying of Russian's propagondons
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  yalo: ^2.0.3
  isolator: ^2.0.2
  provider: ^6.0.2
  flutter_markdown: ^0.6.9
  url_launcher: ^6.0.20
  dio: ^4.0.4
  yalo_locale:
    path: ./.yalo_locale

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/